apiVersion: v1
kind: Service
metadata:
  name: myapp
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000 # بورت الأبلكيشن جوه الـ Container
      nodePort: 30007  # البورت الخارجي اللي هيتفتح على الـ Node وتقدر تفتح بيه الأبلكيشن في المتصفح